const Categories = [
  {
    id: 1,
    title: "Men's Black Shirt",
    price: "950",
    category: "Men",
    image: "../image.jpg",
  },

  {
    id: 2,
    title: "Men Full Sleeve Solid Sweatshirt",
    price: "2,099",
    category: "Men",
    image: "../hood.jpg",
  },
  {
    id: 3,
    title: "Men Grey Viscose Rayon Trousers",
    price: "2,299",
    category: "Men",
    image: "../pant.jpg",
  },
  {
    id: 4,
    title: "Nike REVOLUTION Shoes For Men",
    price: "1,798",
    category: "Men",
    image: "../shoe.jpg",
  },
  {
    id: 5,
    title: "Puma Axelion Shoes For Men",
    price: "3,450",
    category: "Men",
    image: "../puma.jpg",
  },
  {
    id: 6,
    title: "CROCS Bayaband Slides ",
    price: "1,198",
    category: "Men",
    image: "../crocs.jpg",
  },
  {
    id: 7,
    title: "Leadcat 2.0 NJR Slides",
    price: "1,374",
    category: "Men",
    image: "../pumaslipper.jpg",
  },
  {
    id: 8,
    title: "Solid Men Blue Chino Shorts",
    price: "2,999",
    category: "Men",
    image: "../shorts.jpg",
  },
  {
    id: 9,
    title: "Printed Men White Chino Shorts",
    price: "1,049",
    category: "Men",
    image: "../whiteshort.jpg",
  },

  {
    id: 10,
    title: "Self Design Bollywood Cotton Silk Saree",
    price: "650",
    category: "Women",
    image: "../image1.jpg",
  },
  {
    id: 11,
    title: "Women's Salwar Cotton Silk,beautiful single fleet fabric",
    category: "Women",
    price: "1,500",
    image: "../salwar.jpg",
  },
  {
    id: 12,
    title: "Floral Print Bollywood Lycra Blend Saree ",
    price: "999",
    category: "Women",
    image: "../greensaree.jpg",
  },
  {
    id: 13,
    title: "Self Design Bollywood Cotton Silk Saree",
    category: "Women",
    price: "899",
    image: "../bluesaree.jpg",
  },
  {
    id: 14,
    title: "Woven Kanjivaram Pure Silk, Art Silk Saree ",
    price: "5000",
    category: "Women",
    image: "../pattusaree.jpg",
  },
  {
    id: 15,
    title: "Printed Bandhani Georgette Saree, Art Silk Saree ",
    price: "1,999",
    category: "Women",
    image: "../bathani.jpg",
  },
  {
    id: 16,
    title: "Slides ",
    price: "1,399",
    category: "Women",
    image: "../white.jpg",
  },
  {
    id: 17,
    title: "Shasmis Women's Georgette Digital Floral Printed ",
    price: "749",
    category: "Women",
    image: "../dress.jpg",
  },
  {
    id: 18,
    title: "Women's Blue Woven Cotton Western Dress",
    price: "722",
    category: "Women",
    image: "../dress1.jpg",
  },

  {
    id: 19,
    category: "Mobiles",
    title: "APPLE iPhone 11 (White, 64 GB)",
    image: "../iphone11.jpg",
    price: "37,999",
    Descripition: "64 GB ROM",
    Proccessor: "A13 Bionic Processor",
  },
  {
    id: 20,
    category: "Mobiles",
    title: "SAMSUNG Galaxy F22 ( Blue, 64 GB)",
    image: "../f22blue.jpg",
    price: "10,499",
    Descripition: "4 GB RAM | 64 GB ROM ",
    Proccessor: "MediaTek Helio G80 Processor",
  },
  {
    id: 21,
    category: "Mobiles",
    title: "SAMSUNG Galaxy F22 128 GB",
    price: "12,499",
    image: "../f22black.jpg",
    Descripition: "6 GB RAM | 128 GB ROM ",
    Display: "16.26 cm (6.4 inch) HD+ Display",
    Proccessor: "MediaTek Helio G80 Processor",
  },
  {
    id: 22,
    category: "Mobiles",
    title: "Realme C20 | Dark Grey, 64 GB)",
    price: "8,499",
    image: "../c20.jpg",
    Descripition: "4 GB RAM | 128 GB ROM",
    Display: "16.26 cm (6.4 inch) HD+ Display",
    Proccessor: "MediaTek Helio G80 Processor",
  },
  {
    id: 23,
    title: "APPLE iPhone 12 (Purple, 64 GB)",
    price: "37,999",
    image: "../i12.jpg",
    category: "Mobiles",
    Descripition: "64 GB ROM",
    Display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
    Proccessor: "A14 Bionic",
  },
  {
    id: 24,
    title: "APPLE iPhone 13 (Black, 128 GB)",
    price: "42,999",
    category: "Mobiles",
    image: "../iphone13.jpg",
    Descripition: "128 GB ROM",
    Display: "15.49 cm (6.1 inch) Liquid Retina HD Display",
    Proccessor: "A15 Bionic",
  },
  {
    id: 25,
    category: "Mobiles",
    title: "POCO C31 ( Blue, 64 GB)",
    image: "../poco.jpg",
    price: "7,999",
    Descripition: "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB",
    Display: "16.59 cm (6.53 inch) HD+ Display",
    Proccessor: "MediaTek G35 Processor",
  },

  {
    id: 26,
    category: "Electronics",
    title: "Mi X Series 108 cm Ultra HD (4K) LED Smart Android TV ",
    image: "../mitv.jpg",
    price: "26,999",
    Descripition:
      "With this Xiaomi TV that breathes life into your entertainment",
    Display: "4k Display",
  },
  {
    id: 26,
    category: "Electronics",
    title: "SAMSUNG Crystal 4K Neo Series 108 cm (43 inch)  ",
    image: "../samsung.jpg",
    price: "28,999",
    Descripition:
      "With this Samsung TV that breathes life into your entertainment",
    Display: "4k Display",
  },
  {
    id: 26,
    category: "Electronics",
    title: "OnePlus Y1S Pro 138 cm (55 inch) ",
    image: "../oneplustv.jpg",
    price: "36,999",
    Descripition:
      "With this Oneplus TV that breathes life into your entertainment",
    Display: "4k Display",
  },
  {
    id: 26,
    category: "Electronics",
    title: "Blue Star Convertible 1.5 Ton 3 AC",
    image: "../Ac1.jpg",
    price: "35,990",
    Descripition:
      "With Star Split Inverter Multi Sensors, Stabalizer Free Operation",
  },
  {
    id: 26,
    category: "Electronics",
    title: "Daikin 1.5 Ton AC - White ",
    image: "../daikin.jpg",
    price: "36,999",
    Descripition:
      "Auto Restart No need to manually reset the settings post power-cut",
  },
  {
    id: 26,
    category: "Electronics",
    title: "LG 8 kg Fully Automatic Front Load Washing Machine ",
    image: "../washing.jpg",
    price: "34,490",
    Descripition:
      "Fully Automatic Front Load Washing Machines have Great Wash ",
  },
  {
    id: 26,
    category: "Electronics",
    title: "BOSCH 7 kg 1200 Fully Automatic Front Load Washing Machine ",
    image: "../washing1.jpg",
    price: "31,990",
    Descripition: "1200 RPM Higher the spin speed, lower the drying time",
  },
  {
    id: 26,
    category: "Electronics",
    title:
      "Haier 304 L Frost Free Double Door 3 Star Convertible Refrigerator   ",
    image: "../fridge.jpg",
    price: "40,999",
    Descripition: "Frost Free  Auto fridge defrost to stop ice-build up",
  },
  {
    id: 26,
    category: "Electronics",
    title: "ASUS ROG Strix G15 Ryzen 7 Octa Core AMD R7-4800H",
    image: "../laptop.jpg",
    price: "84,999",
    Descripition:
      "(16 GB/1 TB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 3050 Ti/144 Hz) G513IE-HN040WS Gaming Laptop",
  },
  {
    id: 26,
    category: "Electronics",
    title: "ASUS Zenbook 14 OLED (2023) Ryzen 5 Hexa Core 7530U ",
    image: "../asus.jpg",
    price: "91,997",
    Descripition:
      "Finger Print Sensor for Faster System Access,Light Laptop without Optical Disk Drive",
  },
  {
    id: 27,
    category: "Gadgets",
    title: "ZEBRONICS 100HB High Speed ZEB-100HB USB Hub  (Black)",
    image: "../gad.jpg",
    price: "289",
    Descripition:
      "Zeb-100HB is a compact USB hub that comes with a compact design that can fit into a pocket or a wallet",
  },
  {
    id: 28,
    category: "Gadgets",
    title: "Woomzy Mini Hand Free Portable Neckband Fan USB Rechargeable",
    image: "../gad2.jpg",
    price: "989",
    Descripition:
      "Woomzy NECK-FAN? 20H WORKING: 9000mAh USB neck fan large capacity batteries provide 9-20hrs working hours duration",
  },
  {
    id: 29,
    category: "Gadgets",
    title:
      "AmazingGadgets Adjustable 360 degree Bike Holder Rack Bicycle Bottle Holder",
    image: "../gad3.jpg",
    price: "399",
    Descripition:
      "Fits to most of the bicycles with or without bottle rack holder cage High quality plastic materials",
  },
  {
    id: 30,
    category: "Gadgets",
    title:
      "Gadget Five Edge To Edge Tempered Glass for -Poco X2, Redmi K30 High quality plastic materials",
    image: "../gad4.jpg",
    price: "265",
    Descripition:
      " Premium tempered glass processed shield, provides extensive protection from outside damages and scratches ",
  },
  {
    id: 31,
    category: "Gadgets",
    title: "Bhavi Hub Multipor TypeC_5in1_HDMI_hub USB Hub  (Gray)",
    image: "../gad5.jpg",
    price: "1,502",
    Descripition:
      "Strong compatibility, support for mobile phones such as Samsung S9, S10 and so on",
  },
  {
    id: 32,
    category: "Gadgets",
    title: "Gadget Zone USB Type C Cable 6.5 A 1.00494999999996 ",
    image: "../gad6.jpg",
    price: "394",
    Descripition:
      "Amunguss Fast Charging USB Type C Cable - Designed for all Type C devices and Supports both Data Sync and Charging functions",
  },
  {
    id: 33,
    category: "Gadgets",
    title: "Mi by Xiaomi Grooming Kit Grooming Kit 90 min  (Black)",
    image: "../gad7.jpg",
    price: "1,649",
    Descripition:
      "You can always stay neat and well-groomed with the Xiaomi Mi XMGHT2CKITLF Grooming Kit. Featuring different attachments",
  },
];

export default Categories;
